export const TEXT = {
    MESSAGE: {
        UPDATE_SUCCCESS: 'Update successful',
        CREATE_SUCCESS: 'Create successful',
        REQUIRED_FIELD: (name: string) => `Please enter a value for the '${name}' field.`,
        EMAIL_FIELD: `Please enter a valid email address.`,
    },
    BUTTON_TEXT: {
        UPDATE: 'Update',
        CANCEL: 'Cancel',
        ADD: 'Add',
        EDIT: 'Edit',
        SEARCH: 'Search',
        RESET: 'Reset',
        REGISTER: 'Register',
        LOGIN: 'Login',
    },
    TITLE: {
        USER: 'User',
        USER_CREATE: 'Create User',
        USER_EDIT: 'Edit User',
        PERMISSION: 'Permission',
        PERMISSION_CREATE: 'Create Permission',
        PERMISSION_EDIT: 'Edit Permission',
        ROLE: 'Role',
        ROLE_CREATE: 'Create Role',
        ROLE_EDIT: 'Edit Role',
        JOB: 'Job',
        JOB_CREATE: 'Create Job',
        JOB_EDIT: 'Edit Job',
        COMPANY: 'Company',
        COMPANY_CREATE: 'Create Company',
        COMPANY_EDIT: 'Edit Company',
        RESUME: 'Resume',
        RESUME_CREATE: 'Create Resume',
        RESUME_EDIT: 'Edit Resume',
    },
    AUTOCOMPLETE: {
        MALE: 'Male',
        FEMALE: 'Female',
        METHODS: ['GET', 'POST', 'PATCH', 'DELETE'],
        STATUS: ['PENDING', 'REVIEWING', 'APPROVED', 'REJECTED'],
    },
};
