import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/header/Header";
import ThemeRegistry from "@/provider/ThemeRegistry";
import "@/api/apiConfig";
import { ReduxProvider } from "@/provider/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ReduxProvider>
                    <ThemeRegistry options={{ key: "mui" }}>
                        <Header />
                        {children}
                    </ThemeRegistry>
                </ReduxProvider>
            </body>
        </html>
    );
}
