import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/admin/navbar/Navbar";
import Header from "@/components/admin/header/Header";
import ThemeRegistry from "@/provider/ThemeRegistry";
import "@/api/apiConfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeRegistry options={{ key: "mui" }}>
                    <div className="flex">
                        <div className="basis-60 bg-gray-500/10 h-screen">
                            <Navbar />
                        </div>

                        <div className="bg-gray-300/10 basis-full h-screen flex flex-col">
                            <div className="bg-green-400/10 h-20">
                                <Header />
                            </div>
                            <div className="bg-red-400/10 flex-grow">{children}</div>
                        </div>
                    </div>
                </ThemeRegistry>
            </body>
        </html>
    );
}
